[package]
name = "archive"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
algo_lib = {path = "../algo_lib"}
chrono = "~0.4"
fs_extra = "~1.2"